default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: help_desk_development
  username: help_desk
  password: Pooks123
  host: localhost

test:
  <<: *default
  database: help_desk_test
  username: help_desk
  password: Pooks123
  host: localhost